spring:
  profiles: 
     active: native
  cloud:
    config:
      server:
        git:
          uri: https://github.com/PradeepInsys/PMS/
          search-paths:
            - "config-properties/authServer/default/dev"

