spring:
  kafka:
    consumer:
      group-id: email_consumer
  
  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb?autoReconnect=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: gupta.pradeepkumar07@gmail.com
    password: 78787878
    properties.mail.smtp:
      auth: true
      starttls.enable: true
security:
  basic:
    enabled: false
